# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mamaskitchen', '0003_foodtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='menuitems',
            new_name='itemstype',
        ),
    ]
